In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px
from plotly.subplots import make_subplots
import plotly.graph_objects as go
from statsmodels.stats.weightstats import ztest

In [ ]:
data = pd.read_csv('/content/BankChurners.csv')
data = data.drop(['Naive_Bayes_Classifier_Attrition_Flag_Card_Category_Contacts_Count_12_mon_Dependent_count_Education_Level_Months_Inactive_12_mon_1','Naive_Bayes_Classifier_Attrition_Flag_Card_Category_Contacts_Count_12_mon_Dependent_count_Education_Level_Months_Inactive_12_mon_2'],axis=1)
data.head()

   CLIENTNUM     Attrition_Flag  ...  Total_Ct_Chng_Q4_Q1 Avg_Utilization_Ratio
0  768805383  Existing Customer  ...                1.625                 0.061
1  818770008  Existing Customer  ...                3.714                 0.105
2  713982108  Existing Customer  ...                2.333                 0.000
3  769911858  Existing Customer  ...                2.333                 0.760
4  709106358  Existing Customer  ...                2.500                 0.000

[5 rows x 21 columns]

In [ ]:
data['Credit_Limit'].skew()

1.666725807993647

In [ ]:
data['Credit_Limit'].describe()

count    10127.000000
mean      8631.953698
std       9088.776650
min       1438.300000
25%       2555.000000
50%       4549.000000
75%      11067.500000
max      34516.000000
Name: Credit_Limit, dtype: float64

In [ ]:
"""Q: hipotesis apakah rata-rata credit limit laki-laki dan perempuan sama? 
H0: Tidak, credit limit tidak ada hubungannya dengan gender.
H1: Sama
CI = 95%
a = 0.05"""

data.groupby('Gender').agg(Credit_Limit = ('Credit_Limit','mean'))

        Credit_Limit
Gender
F        5023.854274
M       12685.674963

In [ ]:
male = data.loc[(data['Gender']=='M')].sample(n=50)
female = data.loc[(data['Gender']=='F')].sample(n=50)

In [ ]:
#menggunakan ztest karena sample lebih dari 50
#menggunakan 2 variable untuk menguji apakah rata-rata kedua variable tersebut sama atau tidak

ztest, pvalue = ztest(x1=male['Credit_Limit'], x2=female['Credit_Limit'],value=0,alternative='two-sided')

print('ztest: {} and pvalue: {}'.format(ztest,pvalue))

ztest: 3.62163323072596 and pvalue: 0.00029274897239789973

In [ ]:
alpha = 0.05

if pvalue < alpha:
  print('Result:')
  print('Hypothesis False')
  print('pvalue: {} < alpha {}'.format(pvalue,alpha))
else:
  print('Result:')
  print('Hypothesis True')
  print('pvalue: {} > alpha: {}'.format(pvalue,alpha))

Result:
Hypothesis False
pvalue: 0.00029274897239789973 < alpha 0.05